### ISSUE TITLE
Convert glamor to a monorepo

### ISSUE THREAD

**Issue by donaldpipowitch** [threepointone/glamor#204]
This is a **breaking change** and part of the `v3` roadmap: https://github.com/threepointone/glamor/issues/83.

# Motivation

To make it easier for glamor to add support for additional frameworks (e.g. #194) it would be useful, if we can publish framework level support as standalone packages. Framework specific dependencies can be managed separately and discoverability like the search on [npmjs.com](https://www.npmjs.com/) will better as we can tag the packages accordingly.

As an added benefit we probably get better tooling support in certain situations (e.g. better handling for TypeScript declarations as mentioned here: https://github.com/threepointone/glamor/pull/49#issuecomment-246090363).

# Migration

See [here](https://github.com/threepointone/glamor/blob/master/docs/migration.md#independent-packages).

# TODOs

- [x] Move to Lerna
  - #195 - Thank you, @ChristopherBiscardi.
  - #205, #206 - Thank you, @otbe.
- [x] Write a migration guide. ([docs](https://github.com/threepointone/glamor/blob/master/docs/migration.md#independent-packages))
- [ ] Publish a `v2` patch release with deprecation warnings.
  - #207
- [ ] Publish a `v3` prerelease.

**Comment by donaldpipowitch** [comment]
Note: It looks like some packages still miss a `package.json` (e.g. [here](https://github.com/threepointone/glamor/tree/v3/packages/glamor-ous)). The `version` in `lerna.json` probably needs to match the version in the packages, too (see [here](https://github.com/threepointone/glamor/blob/v3/lerna.json#L6)).

**Comment by ChristopherBiscardi** [comment]
`lerna publish --npm-tag=next` would publish the next tag instead of latest [as documented here](https://github.com/lerna/lerna#--npm-tag-tagname)

**Comment by donaldpipowitch** [comment]
Thanks. Okay, I've found that, too. But should I need to run `$ npm version premajor` in every package beforehand? (And later `prerelease` instead of `premajor`?) Or do I need to write the version I want in `lerna.json` and then run your command and lerna changes the versions of the packages?

**Comment by ChristopherBiscardi** [comment]
Lerna will bump the sub packages when publishing. There is no need to maintain the version number in any sub packages. The only version that matters is lerna.json, which is controlled and bumped by lerna. [Here is what publish does](https://github.com/lerna/lerna#publish)

**Comment by donaldpipowitch** [comment]
Nevermind... I get a prompt to choose the version after `lerna publish`, right? 👍

**Comment by donaldpipowitch** [comment]
Thanks.

**Comment by otbe** [comment]
Btw: is there any reason why we not use a scoped package name (a la @glamor) for all the packages? I think it may help to distinguish between glamor supported and community provided packages (glamor-react vs @glamor/react)

**Comment by donaldpipowitch** [comment]
I guess it was easier to start without scoped packages (no need to create a new npm user, no need to migrate `glamor` to something like `@glamor/core` or so...), but no other real reason...? ¯\_(ツ)_/¯

Anyone who has an opinion on this? :)

**Comment by otbe** [comment]
¯\(°_o)/¯

**Comment by ChristopherBiscardi** [comment]
I did it as global packages in the initial PR because I wanted to get code up for review and separate package names was one less thing to discuss/deal with.

It's interesting to note that babel keeps the public namespace and that this works well for the scale of community-level plugins (and presets, etc), but I've also seen people grab names such as `babel-preset-201xx` who aren't affiliated with the babel project. If we use `@glamor/*`, I feel like it would still be weird to have a different project own the equivalent `glamor-*` package but don't have a strong opinion either way.

**Comment by donaldpipowitch** [comment]
@otbe Looks like no one has a strong opinion about that. I'd pass the decision to you 😃  If you'd like to use scoped packages, feel free to create a new npm user 😄  Looks like [glamor](https://www.npmjs.com/~glamor) is still free. If we want that, we'd still need to rename the original `glamor`. After thinking about it I wouldn't recommend something like `@glamor/core`, because I think people could think that they would _need_ another package to use glamor. When `css` becomes our bread and butter function (see #83) we could use `@glamor/css`. IMHO that would be a good name.

**Comment by KyleAMathews** [comment]
I have strong opinions :-) I think that there's not a single open source project that I know that uses scoped packages is an excellent reason for us to not use them.

Using scoped packages has no advantage so would needlessly confuse a high percentage of potential users. Let's just stick with gatsby-*.

**Comment by KyleAMathews** [comment]
Haha I meant glamor-*

**Comment by donaldpipowitch** [comment]
Thank you. I highly appreciate feedback on this!

**Comment by otbe** [comment]
I cant imagine a reason why using @glamor should confuse anyone. Most of the time it is auto-imported (in case of TS) or at least autocompleted (path completion) while typing but nevertheless my opinion on this is not so strong. Lets keep glamor-* :)

By the way cycle uses scoped packages :)

**Comment by threepointone** [comment]
I don't have a strong opinion on this, so I'll leave it up to you folks. I'd personally recommend keeping glamor-*, and don't mind other folks trying to get in on the fun, even if they're not part of the org. babel does this, no problems. 

[btw, I'm just loving what you folks are doing. spending today to absorb the progress, will jump in once I'm comfortable]

**Comment by threepointone** [comment]
and about time we add @ChristopherBiscardi to collaborators, I think? :) 
[just did]

**Comment by donaldpipowitch** [comment]
I just merged #207. @otbe just said that he probably wants to fix #210 soon. When he did this I'd publish the first v3 prerelease and release a v2 with deprecation warnings.

**Comment by ChristopherBiscardi** [comment]
thanks for the add @threepointone :)

@donaldpipowitch I'll have #210 fixed soon.

**Comment by donaldpipowitch** [comment]
https://github.com/threepointone/glamor/issues/210 is closed now. Now I'll wait for a review of https://github.com/threepointone/glamor/pull/214, because we added https://github.com/threepointone/glamor/pull/212 to the `v3` branch in the meantime. :)

After that everything should be fine for the first prerelease 😍

**Comment by donaldpipowitch** [comment]
Published 🎉 

```
$ npm i glamor@next
glamor@3.0.0-1

$ npm i glamor@latest
glamor@2.20.24
```

**Comment by electerious** [comment]
There's a depreciation message in the current version which links to this issue.

```
[Deprecation] In glamor v3 this file will be published as a standalone package: "glamor-server". See https://github.com/threepointone/glamor/issues/204 for more information.
```

It's confusing because this issue doesn't contain any information for users of glamor. How does it effect me? What should/can I do? What is *this file*?

The [glamor-server](https://www.npmjs.com/package/glamor-server) readme is also empty and no help. I guess this will change soon, but at the moment the message is more confusing than helpful.

**Comment by ChristopherBiscardi** [comment]
@electerious thanks for the feedback. In this case, it means that [renderStatic](https://github.com/threepointone/glamor/blob/e38b0dbd6ebdfde9876c2aba2df3868728d0de07/packages/glamor-server/src/index.js#L10) and renderStaticOptimized are being moved to the `glamor-server` package in v3 (as opposed to `glamor/server`). There is [a migration doc](https://github.com/threepointone/glamor/blob/v3/docs/migration.md#independent-packages) in the v3 branch.

**Comment by donaldpipowitch** [comment]
You probably imported the file `glamor/server` somewhere, right? This file will not be part of glamor in `v3`. It will (and currently is as a prerelease) published as a standalone package.
You can find more information in the [migration guide](https://github.com/threepointone/glamor/blob/master/docs/migration.md#independent-packages) linked in the first comment.

Thank you for your feedback. After your comment I think we could have found a better message for this deprecation. Instead of:

```
[Deprecation] In glamor v3 this file will be published as a standalone package: "glamor-server". See https://github.com/threepointone/glamor/issues/204 for more information.
```

This would maybe better:

```
[Deprecation] You imported `glamor/server`. This file will not be a part of the next major release of glamor. It will be published as a standalone package called "glamor-server" instead. See https://github.com/threepointone/glamor/issues/204 for more information.
```

I'll also update the first comment to better reflect this.

**Comment by electerious** [comment]
Thanks for the help and clarification! :) The proposed message is less confusing.
