### ISSUE TITLE
Consolidating previous API set to `css()` and switch to TypeScript

### ISSUE THREAD

**Issue by donaldpipowitch** [threepointone/glamor#229]
This is a **breaking change** and part of the `v3` roadmap: https://github.com/threepointone/glamor/issues/83.

# Motivation

As described in the first post of https://github.com/threepointone/glamor/issues/83 we want to reduce the API surface of Glamor to make it easier to learn and maintain.

What we discussed so far:
* **Every API** described in [`helpers.md`](https://github.com/threepointone/glamor/blob/master/docs/helpers.md) will be deprecated. 
* We _don't_ move the deprecated APIs into a `glamor/helpers` package or something similar, because everything they do can be achieved with `css()` as well. So we just have to teach _one_ way.

We discussed moving to TypeScript earlier (https://github.com/threepointone/glamor/issues/83#issuecomment-275614976) and as a lot of code needs to be changed in this step anyway I think it is good idea to do it now. It is probably the best to switch to TypeScript as soon as possible anyway for future refactoring.

# Migration

A link with migration steps will be placed here in the future.

# TODOs

- [x] Remove deprecated APIs in v3 branch. (https://github.com/threepointone/glamor/pull/231)
- [x] Switch to TypeScript (for `glamor` package). (https://github.com/threepointone/glamor/pull/269)
- [ ] Add deprecation warnings in v2.
- [ ] Write a migration guide.

**Comment by kentcdodds** [comment]
Will the helpers be moved to another package? I think that having helpers is really handy and it's one of the things I like about glamor. Also, what will become of `simulate`?

**Comment by donaldpipowitch** [comment]
Great questions and exactly what I'd like to discuss.

> Will the helpers be moved to another package?

I'd say if enough people are interested in this, we can do that. 👍  But I would not want to do that, if it is not really used by anyone.

Do you _need_ these helpers or are you just _used_ to them? Everything can be achieved just by using the more generic `css()` and most people I talked to find that a little bit easier to read and use.

> Also, what will become of simulate?

`simulate()` is not directly defined in `helpers.md` and its functionality is not something which can be done by using `css()` (AFAIK). So I wouldn't say it becomes deprecated.

**Comment by kentcdodds** [comment]
Yeah, I kinda feel like it'd be easier to teach people the `css` API really well and reduce the amount of magic as much as possible. So yeah, let's not make a `glamor-helpers` package for now :+1:

**Comment by fredguest** [comment]
The inability to prefix class names with meaningful words is the only downside of using Glamor for me personally, makes debugging in browser dev tools incredibly and unnecessarily challenging. Would love to see this addresses in 3.0 https://github.com/threepointone/glamor/issues/129

**Comment by donaldpipowitch** [comment]
@fredguest Yeah, the debugging story could definitely be improved. We only have _labels_ so far. If you want to you can tell us in #83 what you need, which browsers do you use for debugging and so on. I personally would like to test source maps for inline styles "one day" which would help a lot. But it is not a topic for _this_ specific issue.

**Comment by fredguest** [comment]
My bad, I interpreted this comment you made in #83 "I created a new issue for the changes I think which qualify for the next possible prerelease step: #229", to mean that _this_ issue would be the place to discuss future features. Carry on!

**Comment by donaldpipowitch** [comment]
Sorry for the confusion :) I meant #83 is for general discussion and that #229 - when it is finished - can be the next _prerelease_. We want to publish v3 in multiple steps. Every step as its own prerelease.

**Comment by fredguest** [comment]
Makes perfect sense. The level of organization you've been bringing to this lib is awesome btw! 👌🏼

**Comment by donaldpipowitch** [comment]
Thank you :)

**Comment by mkitt** [comment]
I definitely appreciate a smaller footprint in the api, keeping the learning curve at a minimum and keeping unnecessary code out of the core of glamor. While I don't necessarily _need_ the helpers being able to write styles like:

```js
const sectionStyle = compose(flex, justifyCenter, alignCenter, media(minBreak3, px40))
const buttonStyle = compose(bold, alignRight, colorBlue, hover(colorRed))

const AboutView = () =>
  <section className={sectionStyle}>
    <TextButon className={buttonStyle}>Button</TextButton>
  </section>
```
☝️ Pretty, succinct and no strings!

So my vote is to at least have the helpers out there somewhere.

Thanks for a great library!

**Comment by kentcdodds** [comment]
Haha, check this out: https://github.com/threepointone/glamor/blob/master/src/index.js#L620

```js
export const compose = css
```

I think all you really need is `css` ;-)

**Comment by mkitt** [comment]
Totally with compose, merge and style, linking to css 👍. Those should go. 

I was more referring to the [pseudo](https://github.com/threepointone/glamor/blob/master/src/index.js#L630) and [media](https://github.com/threepointone/glamor/blob/master/src/index.js#L622) functions in my example. 

All of these helpers are pretty easy to replicate though and may make more sense to add them at the project level.

**Comment by donaldpipowitch** [comment]
For helper functions like `media()` which take arguments which are often shared across the whole project, we do something like that:

```js
const tablet = '@media(min-width: 48rem)';

const style = css({
  color: 'red',
  [tablet]: {
    color: 'green'
  }
});
```

Maybe this can be seen as less "magical" than using `media()` when you start learning Glamor. Why `media()` isn't magical at all, you have to look into the source code to see that it does basically the same. If you use TypeScript and hover over `tablet` you can even see the raw string value which was initially used. That would not be possible with `media()`, but it can be useful every now and then.

---

You _could_ do that for most helper functions, if you just want to avoid using strings:

```js
const hover = ':hover';

const style = css({
  color: 'red',
  [hover]: {
    color: 'green'
  }
});
```

**Comment by maxdeviant** [comment]
I'd be happy to help with rewriting/refactoring some of the packages to TypeScript :+1:

**Comment by donaldpipowitch** [comment]
Regarding TypeScript conversation: https://github.com/threepointone/glamor/issues/242#issuecomment-294260385

**Comment by donaldpipowitch** [comment]
`glamor@3.0.0-2` with TypeScript can be tested :)

**Comment by threepointone** [comment]
👏👏👏exciting! Thank you!

**Comment by threepointone** [comment]
closing this, will revisit when new plans for v3 are concrete.
